version: '3.8'
services:
  flutter-web:
    image: shumaimiftikhar/linguaverse:latest
    container_name: linguaverse_app
    ports:
      - "80:80"
    restart: unless-stopped

  firebase-db:
    image: andreysenov/firebase-tools
    container_name: linguaverse_db
    ports:
      - "4000:4000"
      - "8082:8080"
    volumes:
      - firebase_data:/home/node       # persistent volume ✅
    command: firebase emulators:start --only firestore --project demo-linguaverse

volumes:
  firebase_data:
